#!/usr/bin/env bash

exit_status=0
RED='\033[0;31m'
GREEN='\033[0;32m'
NO_COLOR='\033[0m'

declare -A checks=(
    [Psalm]="vendor/bin/psalm --no-cache"
    [PHPUnit]="vendor/bin/phpunit --color --testdox"
)

echo ""

for check_name in "${!checks[@]}"; do
    echo -en "\rPerforming pre-commit check: ${check_name} ... "

    out=$(${checks[$check_name]} 2>&1)

    if [ $? -eq 0 ]; then
        echo -e "${GREEN}success :)${NO_COLOR}"
    else
        echo -e "${RED}failed!${NO_COLOR}"
        echo "---------------------------------------------------"
        echo "$out"
        echo "---------------------------------------------------"
        echo ""
        exit_status=1
    fi
done

exit $exit_status