#!/usr/bin/env bash

exit_status=0
RED='\033[0;31m'
GREEN='\033[0;32m'
NO_COLOR='\033[0m'

declare -A checks=(
    [unit-tests]="composer run unit-tests"
    [coding-standards]="composer run coding-standards"
    [static-analysis]="composer run static-analysis"
    [mutation-tests]="composer run mutation-tests"
)


function perform_check {
    local check_name="$1"

    printf "\r  > %-16s ... " ${check_name}

    OUTPUT=$(${checks[$check_name]} 2>&1)

    if [ $? -ne 0 ]; then
        echo -e "${RED}failed!${NO_COLOR}"
        echo "---------------------------------------------------"
        echo "$OUTPUT"
        echo "---------------------------------------------------"
        echo ""
        return 1
    fi

    echo -e "${GREEN}success${NO_COLOR}"
    return 0
}

echo ""
echo "Starting checks:"

for check_name in "${!checks[@]}"; do
    if ! perform_check $check_name; then
        exit_status=1
    fi
done

echo ""

exit $exit_status