name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1']
        composer_update:
          - 'composer update --prefer-stable --prefer-lowest'
          - 'composer update --prefer-stable'

    steps:
    
    - name: Setup PHP environment
      uses: nanasess/setup-php@v3.0.8
      with:
        php-version: ${{ matrix.php }}

    - name: Upgrade libpcre2-8-0
      run: sudo apt update && sudo apt install -y libpcre2-8-0

    - uses: actions/checkout@v2

    - name: Show PHP version and modules
      run: |
        php -v
        php -m

    - name: Install dependencies
      run: ${{ matrix.composer_update }}

    - name: Run Unit tests
      run: vendor/bin/phpunit --color --testdox

    - name: Static analysis - Psalm
      run: vendor/bin/psalm --no-cache
    
    - name: Check coding standards
      run: vendor/bin/php-cs-fixer fix --diff --allow-risky=yes --dry-run
