name: CI Pipeline

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1']
        composer_update:
          - 'composer update --prefer-stable --prefer-lowest'
          - 'composer update --prefer-stable'

    steps:
    
    - name: Setup PHP environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
    
    - uses: actions/checkout@v2

    - name: Show PHP version and modules
      run: |
        php -v
        php -m

    - name: Install dependencies
      run: ${{ matrix.composer_update }}

    - name: Run Unit tests
      run: vendor/bin/phpunit --color --testdox

    - name: Static analysis - Psalm
      run: vendor/bin/psalm --no-cache

    - name: Mutation testing - Infection
      run: vendor/bin/infection -j4 --ansi --show-mutations --no-interaction
    
    - name: Check coding standards
      run: vendor/bin/php-cs-fixer fix --diff --allow-risky=yes --dry-run
      if: matrix.php != '8.1'
