name: CI Pipeline

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1']
        composer_update:
          - 'composer update --prefer-stable --prefer-lowest'
          - 'composer update --prefer-stable'

    steps:
    
    - name: Setup PHP environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
    
    - uses: actions/checkout@v2

    - name: Show PHP version and modules
      run: |
        php -v
        php -m

    - name: Install dependencies
      run: ${{ matrix.composer_update }}

    - name: Run Unit tests
      run: composer run unit-tests

    - name: Static analysis - Psalm
      run: composer run static-analysis

    - name: Mutation testing - Infection
      run: composer run mutation-tests
    
    - name: Check coding standards
      run: composer run coding-standards
      if: matrix.php != '8.1'
